# Generated by Django 3.0 on 2021-09-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description jnsvcosd vsopdv jSP'),
            preserve_default=False,
        ),
    ]
