# Generated by Django 3.0 on 2021-09-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210912_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Clothes'), ('SW', 'Electronics'), ('OW', 'Stationery')], max_length=2),
        ),
    ]
