# Generated by Django 3.0 on 2021-09-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210917_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Clothes'), ('SW', 'Electronics'), ('OW', 'Stationery')], max_length=2),
        ),
    ]
