# Generated by Django 3.0 on 2021-10-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='apartment_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='street_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='zip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
