# Generated by Django 3.0 on 2021-11-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_buyer_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='otp_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='otp_done',
            field=models.BooleanField(default=False),
        ),
    ]
