# Generated by Django 3.0 on 2021-11-09 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_selleritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleritem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Seller'),
        ),
    ]
